name: Infra Plan

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Bicep What-If
        run: |
          az deployment sub what-if \
            --name plan-${{ github.run_number }} \
            --location eastus \
            --template-file bicep/main.bicep \
            --parameters @bicep/parameters/dev.json

      - name: What-If Deployment
        run: |
          az deployment sub what-if \
            --location eastus \
            --template-file bicep/main.bicep \
            --parameters @bicep/parameters/dev.json
